name: nutri_call_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  go_router: ^14.7.2
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.1
  gap: ^3.0.1
  fluttertoast: ^8.2.11
  image_picker: ^0.8.4+4
  permission_handler: ^11.0.1
  percent_indicator: ^4.2.4
  syncfusion_flutter_charts: ^28.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.9.0
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logoApp.PNG"

flutter_gen:
  output: lib/utils/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/navbar/
    - .env